### PR TITLE
updated the function to work with the new get parameter, cleaned up a…

### PR DESCRIPTION
**Pull request by pieterDekker**
… little

### CODE REVIEW

**Comment by pieterDekker** [comment]
@martinavagyan i updated our function, let me know if you want me to document it more, wrt the regexes it might be a little obscure...

**Comment by mavagio** [comment]
@pieterDekker Can you please update the example, on what the regex extracts, the rest is fine.

**Comment by pieterDekker** [comment]
@martinavagyan will this do?

**Comment by mavagio** [comment]
nice!

**Pull request merged**
